// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-GRf86g6pikhnO0FU7Ah_6SM3CttZJlI',
    appId: '1:797825204310:android:e00ae4418b98d43ba2fbf7',
    messagingSenderId: '797825204310',
    projectId: 'mynotes-792da',
    storageBucket: 'mynotes-792da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9l5JXhbblsfF1MbYfy_-Ekv9T3i6B6lA',
    appId: '1:797825204310:ios:ee6360e907d12211a2fbf7',
    messagingSenderId: '797825204310',
    projectId: 'mynotes-792da',
    storageBucket: 'mynotes-792da.appspot.com',
    iosBundleId: 'com.example.notes',
  );

}